# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_workorder_info',
            name='step_status',
            field=models.CharField(default='wait op exec', max_length=30),
        ),
        migrations.AddField(
            model_name='status_workorder_info',
            name='step_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
