# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leader', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('auth', models.BooleanField()),
                ('jumper', models.BooleanField()),
                ('vpn', models.BooleanField()),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
                ('ccj_admin', models.BooleanField()),
                ('cct_admin', models.BooleanField()),
            ],
        ),
    ]
