# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_info',
            old_name='cloud',
            new_name='cloud_type',
        ),
        migrations.RenameField(
            model_name='host_info',
            old_name='types',
            new_name='host_type',
        ),
    ]
