# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(default='/static/assets/images/users/avatar.jpg', max_length=64)),
                ('navigation_title', models.CharField(default='closed', max_length=64)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opmanage.User_info')),
            ],
        ),
    ]
