# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='username',
        ),
    ]
