# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0002_auto_20171201_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='ccj_admin',
            new_name='kibana',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='cct_admin',
            new_name='zabbix',
        ),
    ]
