# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0002_auto_20180201_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lb_info',
            old_name='cloud',
            new_name='cloud_type',
        ),
        migrations.RenameField(
            model_name='lb_info',
            old_name='types',
            new_name='net_types',
        ),
    ]
