# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmanage', '0003_auto_20171203_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
