# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('host_info', models.ManyToManyField(to='opmanage.Host_info')),
            ],
        ),
        migrations.CreateModel(
            name='SaltReturns_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_time', models.DateTimeField()),
                ('tgt', models.CharField(max_length=100)),
                ('fun', models.CharField(max_length=50)),
                ('str_kwarg', models.CharField(max_length=255)),
                ('tgt_type', models.CharField(max_length=15)),
                ('result', models.TextField(db_column='result')),
            ],
        ),
    ]
